# bundle exec jekyll serve --host=0.0.0.0

title: MycilaJSY
description: Arduino / ESP32 library for the JSY1031, JSY-MK-163, JSY-MK-193, JSY-MK-194, JSY-MK-227, JSY-MK-229, JSY-MK-333 families single-phase and three-phase AC bidirectional meters from Shenzhen Jiansiyan Technologies Co, Ltd.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
